### ISSUE TITLE
Pipeline hotfix bug

### ISSUE THREAD

**Issue by MartinezAvellan** [LerianStudio/midaz#402]
## Context
https://github.com/LerianStudio/midaz/actions/runs/12400711636/job/34618555339

Quando abro mais de uma hotfix da develop para main, pelo fato de não ter pre-release o hotfix quebra e não gera release.

> Error: AggregateError: 
>     SemanticReleaseError: The pre-release branches are invalid in the `branches` configuration.
>         at default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/get-error.js:6:10)
>         at file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/branches/index.js:45:19
>         at Array.reduce (<anonymous>)
>         at default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/lib/branches/index.js:35:46)
>         at async run (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/index.js:[68](https://github.com/LerianStudio/midaz/actions/runs/12400711636/job/34618555339#step:5:69):22)
>         at async Module.default (file:///home/runner/work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/index.js:278:22)
>         at async release (/home/runner/work/_actions/cycjimmy/semantic-release-action/v4/src/index.js:31:18)

## How to do it?

validar as hotfix para sempre gerar a release independente se tem pre-release

## Changes

**Comment by MartinezAvellan** [comment]
@lfbarrile01 @GuilhermeMRodrigues
